// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://enhmycayolksjbjmnvzx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVuaG15Y2F5b2xrc2piam1udnp4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc1NDQ4NDgsImV4cCI6MjA2MzEyMDg0OH0.9dsHb_v88Jsp_mjF4IWfxh0WcyUkEacKAhrr-t9_8Kk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);